# Generated by Django 4.2.3 on 2023-07-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CT', 'Clothes'), ('SH', 'Shoes'), ('H', 'Home'), ('BH', 'Beauty & Health'), ('FK', 'Kids'), ('F', 'Food'), ('ST', 'Stationery')], max_length=2, null=True),
        ),
    ]
